spring.application.name=microbizmax

server.port=9090
spring.datasource.url=jdbc:postgresql://ep-lively-firefly-aohzslwd-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_EzxOyW4pPNY5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Prevent lazy loading issues in JSON serialization
spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.open-in-view=true

# Gemini API Key (replace with your actual key)
gemini.api.key=YOUR_GEMINI_API_KEY_HERE
